# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e94b99bea05b7619954a99bd588695815676e594b29928d4b0fcfae7569976585832bcb7300d03ec48c05349ea3b14027d2472185cab776e2ab7e95b97f0f1d0

test:
  secret_key_base: 69db0d9f26028bd7e8ac6782b6a49261ed57eb19282cadc9fae99cfff38864e8d568d2ba40443c29ae2e6cd89b21ed2fc46eb09ddc34042e93e7a788b1a410d9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
